language: ruby
cache: bundler
sudo: false
rvm:
  - 2.4.5
  - 2.5.3
addons:
  apt:
    packages:
    - libgeoip-dev
    - libgeoip1
script: bundle exec rspec spec

services:
  - docker

before_install:
  - docker build -t dap_bats -f Dockerfile.testing .

script:
  - docker build -t dap_bats -f Dockerfile.testing .
  - docker run --rm --name dap_bats -it -e DAP_EXECUTABLE=dap dap_bats /bin/bash -c "find . -name \*.bats | grep -v test/test_helper/ | xargs -n1 bats"
